# User config
author: "Tienda Elymar"
tagline: "Tienda Elymar"
description: "Tu bienestar es nuestra felicidad. La tienda Elymar nace como un proyecto familiar que busca ofrecer productos de calidad en pro de tu binestar, ofrecemos productos de cuidado personal, y demás. Estamos muy agradecidos de tenerte en nuestra página, esperamos que tu experiencia sea la mejor de todas, si tienes alguna pregunta no dudes en conactarnos"
keywords: "Tienda, Tiendaonline, Tienda Elymar"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

# Site config
baseurl: "/elymar"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
